# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12.2
    working_directory: /go/src/github.com/srowles/phonebook
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go get github.com/axw/gocov/...
      - run: go get github.com/AlekSi/gocov-xml
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: mkdir -p test-results/phonebook
      - run: go test -v -coverprofile=c.out 2>&1| go-junit-report > test-results/phonebook/results.xml
      - run: gocov convert c.out | gocov-xml -source /go/src/github.com/srowles/phonebook > test-results/phonebook/cover.xml
      - run: go build -o phonebook.exe cmd/phonebook/main.go
      - store_test_results:
          path: test-results